name: Docker Build and Push to ECR

on:
#   push:
#     branches:
#       - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1

  ECR_BACKEND_REPOSITORY: bookstore-backend
  ECR_FRONTEND_REPOSITORY: bookstore-frontend

  EKS_CLUSTER_NAME: test

jobs:

  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.image-tag.outputs.tag }}

    steps:

      # --------------------------------
      # 1. Checkout source code
      # --------------------------------

      - name: Checkout repository
        uses: actions/checkout@v4


      # --------------------------------
      # 2. Configure AWS using OIDC
      # --------------------------------

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}


      # --------------------------------
      # 3. Get AWS Account ID
      # --------------------------------

      - name: Get AWS Account ID
        id: aws-account
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity \
            --query Account \
            --output text)

          echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV


      # --------------------------------
      # 4. Generate Docker image tag
      # --------------------------------

      - name: Generate image tag
        id: image-tag
        run: |
          TAG=${GITHUB_SHA::7}

          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

          echo "Docker image tag: $TAG"


      # --------------------------------
      # 5. Login to Amazon ECR
      # --------------------------------

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      # --------------------------------
      # 6. Build Backend Docker image
      # --------------------------------

      - name: Build backend image
        run: |
          docker build \
            -t $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_BACKEND_REPOSITORY:${{ steps.image-tag.outputs.tag }} \
            ./backend


      # --------------------------------
      # 7. Build Frontend Docker image
      # --------------------------------

      - name: Build frontend image
        run: |
          docker build \
            -t $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_FRONTEND_REPOSITORY:${{ steps.image-tag.outputs.tag }} \
            ./frontend


      # --------------------------------
      # 8. Push Backend image to ECR
      # --------------------------------

      - name: Push backend image
        run: |
          docker push \
            $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_BACKEND_REPOSITORY:${{ steps.image-tag.outputs.tag }}


      # --------------------------------
      # 9. Push Frontend image to ECR
      # --------------------------------

      - name: Push frontend image
        run: |
          docker push \
            $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_FRONTEND_REPOSITORY:${{ steps.image-tag.outputs.tag }}


      # --------------------------------
      # 10. Show pushed images
      # --------------------------------

      - name: Display image information
        run: |
          echo "Backend image:"
          echo "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_BACKEND_REPOSITORY:${{ steps.image-tag.outputs.tag }}"

          echo ""

          echo "Frontend image:"
          echo "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_FRONTEND_REPOSITORY:${{ steps.image-tag.outputs.tag }}"


  